CFLAGS=-I../shared
CFLAGS+=-lGL -lGLEW -lglfw
a.out : shader_compiler_test.o ../shared/shader_reader.o ../shared/shader_compiler.o
	${CC} ${CFLAGS} $^
a.out : shader_compiler_test.o ../shared/shader_reader.o ../shared/shader_compiler.o
