CFLAGS=-I../shared
CFLAGS+=-lGL -lGLEW -lglfw -lm
a.out : texture_test.o ../shared/shader_reader.o ../shared/shader_compiler.o
	${CC} ${CFLAGS} $^
a.out : texture_test.o ../shared/shader_reader.o ../shared/shader_compiler.o
